name: ${project.name}
version: ${project.version}
description: A plugin to create gates for fast traveling.
depend: [Craft Inc. Gates, dynmap]
author: tomco
website: FIXME
main: de.craftinc.gates.dynmap.Plugin
database: false
