name: ${project.name}
version: ${project.version}
description: A plugin to create gates for fast traveling.
softdepend: [Vault]
author: tomco, s1m0ne
authors: [oloflarsson, locutus, DrAgonmoray, s1m0ne, tomco]
website: FIXME

main: de.craftinc.gates.dynmap.Plugin
database: false
