name: ${project.name}
version: ${project.version}
description: A plugin to create gates for fast traveling.
softdepend: [Craft Inc. Gates, dynmap]
author: tomco
website: http://dev.bukkit.org/bukkit-plugins/craftinc-gates/
main: de.craftinc.gates.dynmap.Plugin
database: false
